//
//  AuthorizationPresenter.swift
//  SpotiSearch
//
//  Created by Reinaldo Villanueva Javierre on 7/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationPresentationLogic
{
  func presentSomething(response: Authorization.Something.Response)
}

class AuthorizationPresenter: AuthorizationPresentationLogic
{
  weak var viewController: AuthorizationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Authorization.Something.Response)
  {
    let viewModel = Authorization.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
