//
//  AuthorizationInteractor.swift
//  SpotiSearch
//
//  Created by Reinaldo Villanueva Javierre on 7/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationBusinessLogic
{
  func doSomething(request: Authorization.Something.Request)
}

protocol AuthorizationDataStore
{
  //var name: String { get set }
}

class AuthorizationInteractor: AuthorizationBusinessLogic, AuthorizationDataStore
{
  var presenter: AuthorizationPresentationLogic?
  var worker: AuthorizationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Authorization.Something.Request)
  {
    worker = AuthorizationWorker()
    worker?.doSomeWork()
    
    let response = Authorization.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
